# -*- coding: utf-8 -*-
"""hw01-tolstoy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dx15mFzfMRluWWnCaaFAZQDuSFHYO-1E
"""

import urllib.request
#Above is a library available to python that forms a request to the site to give me the data from the url
url = "https://www.gutenberg.org/files/2600/2600-0.txt"
#I descided to use the text link cause that was the easiest one to do
file = urllib.request.urlopen(url)
uniqwords = {}
#will hold all the unique words
numWords = 0
for line in file:
  #decoded_line = line.decode("utf-8")
	#print(decoded_line)
  #These were used to help me make sure I could grab the text line by line
  words = line.split()
  for word in words:uniqwords.setdefault(word, 0)
  for word in sorted(uniqwords.keys()):
    numWords = numWords + 1
print("There are ", numWords, "number of unique words.")

